dataset:
  root: '/ssd1/HyunJun/SRCAP/dataset/'
  validation_dataset_json : '/ssd1/HyunJun/SRCAP/dataset/annotations/person_keypoints_val2017.json'
  training_dataset_json : '/ssd1/HyunJun/SRCAP/dataset/annotations/captions_train2017.json'
  crop_size : 16
  upscaling_factor: 4

optimizer:
  name: 'adam'
  weight_decay: 0.0001
  betas: [0.9, 0.999]

scheduler:
  name: 'step'
  scheduler_activate: true
  gamma: 0.1
  total_iters: 1000

inference_mode: 'mode'
learning_rate: 
  discriminator: 0.0001
  generator: 0.00008
num_epochs: 2
num_proposals: 8
d_out_mean: True
batch_size: 10
max_length: 10
fine_tuning: True